language: python
python:
  - "2.7"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - gcc-5
    - g++-5
    - libzmq3-dev

# Install dependencies
install:
  - pip install -r requirements.txt

script:

  # Note: These tests need to be run individually in order to reset global imports
  - python -m unittest tests.model_import.test_import_user_model_single
  - python -m unittest tests.model_import.test_import_user_model_multi_dir
  - python -m unittest tests.model_import.test_import_user_model_multi_file

  # Test with GCC 5
  - export CXX="g++-5"
  - python -m unittest tests.exportcpp.test_basic_example

  # Test with GCC 6
  - export CXX="g++-6"
  - python -m unittest tests.exportcpp.test_basic_example
