language: python
python:
  - "2.7"

#sudo: required
dist: trusty


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.0
    - g++-5.0

#before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -q

# Install dependencies
install:
  - pip install -r requirements.txt
#  - sudo apt-get install gcc-6
#  - export CXX="g++-6"
#  - sudo readlink -f `which c++`
#  - sudo readlink -f `which g++`
#  - sudo g++ -v
#  - sudo g++-6.0 -v

script:

  # Note: These tests need to be run individually in order to reset global imports
  - python -m unittest tests.model_import.test_import_user_model_single
  - python -m unittest tests.model_import.test_import_user_model_multi_dir
  - python -m unittest tests.model_import.test_import_user_model_multi_file
  - python -m unittest tests.exportcpp.test_basic_example
