language: python
python:
  - "2.7"

sudo: false
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5.0 -y

# Install dependencies
install:
  - pip install -r requirements.txt

script:

  # Note: These tests need to be run individually in order to reset global imports
  - python -m unittest tests.model_import.test_import_user_model_single
  - python -m unittest tests.model_import.test_import_user_model_multi_dir
  - python -m unittest tests.model_import.test_import_user_model_multi_file
  - python -m unittest tests.exportcpp.test_basic_example
